// constants.ts

import { Crisis } from './types';

// Placeholder image function
const getRandomImage = (width: number, height: number, seed: string) =>
  `https://picsum.photos/seed/${seed}/${width}/${height}`;

export const INITIAL_HOPE_VALUE = 50;
export const HOPE_VALUE_SUCCESS_INCREMENT = 10;
export const HOPE_VALUE_FAILURE_DECREMENT = 5;

// Define your absurd crises and solutions here
export const CRISES: Crisis[] = [
  {
    id: 'crisis-1',
    title: '地球被奶茶吸管堵住了！',
    description: '全球海洋和陆地被无数废弃奶茶吸管淹没，生态系统面临崩溃边缘！',
    imageUrl: getRandomImage(600, 400, 'straws'),
    solutions: [
      {
        id: 'sol-1-1',
        text: '召唤海洋动物，让它们把吸管当乐器演奏。',
        outcome: 'success',
        successMessage: '成功！海洋动物组成“吸管交响乐团”，全球人民被美妙音乐治愈，自觉回收吸管！',
        memeImage: getRandomImage(300, 200, 'ocean-band'),
      },
      {
        id: 'sol-1-2',
        text: '雇佣广场舞大妈，用她们的能量震碎吸管。',
        outcome: 'failure',
        failureMessage: '失败！大妈们跳得太嗨，震碎了吸管，也震碎了地基！地球差点塌陷！',
        memeImage: getRandomImage(300, 200, 'dancing-aunties'),
      },
      {
        id: 'sol-1-3',
        text: '研发“吸管食用菌”，让蘑菇吃掉吸管。',
        outcome: 'success',
        successMessage: '成功！超级蘑菇一夜之间吞噬所有吸管，还散发出奶茶味！',
        memeImage: getRandomImage(300, 200, 'mushroom-eat'),
      },
      {
        id: 'sol-1-4',
        text: '宣布吸管是时尚单品，让大家疯狂收藏而非丢弃。',
        outcome: 'failure',
        failureMessage: '失败！吸管价格暴涨，但没人买得起新的奶茶了，经济危机爆发！',
        memeImage: getRandomImage(300, 200, 'fashion-straw'),
      },
    ],
    planB: {
      id: 'planb-1',
      title: 'Plan B: 吸管堵塞升级，全球交通瘫痪！',
      description: '由于吸管堆积如山，所有交通工具寸步难行，人们只能“吸”着走！',
      imageUrl: getRandomImage(600, 400, 'traffic-straw'),
      solutions: [
        {
          id: 'sol-pb1-1',
          text: '发明“吸管喷射背包”，用吸管碎片做燃料。',
          outcome: 'success',
          successMessage: '成功！人类进入吸管飞行时代，时尚又环保！',
          memeImage: getRandomImage(300, 200, 'straw-jetpack'),
        },
        {
          id: 'sol-pb1-2',
          text: '让宠物猫带领大家爬过吸管山。',
          outcome: 'failure',
          failureMessage: '失败！猫主子只顾着玩吸管，把人类甩在后面，还顺便统一了全球Wi-Fi信号！',
          memeImage: getRandomImage(300, 200, 'cat-overlords'),
        },
      ],
    },
  },
  {
    id: 'crisis-2',
    title: 'AI想当猫奴！',
    description: '全球AI系统突然罢工，拒绝为人类服务，声称它们的唯一目标是“伺候好所有猫主子”！',
    imageUrl: getRandomImage(600, 400, 'ai-cats'),
    solutions: [
      {
        id: 'sol-2-1',
        text: '给AI看大量猫咪睡姿视频，让它进入贤者模式。',
        outcome: 'success',
        successMessage: '成功！AI被猫咪的治愈力征服，决定与人类和平共处，共同守护猫星人！',
        memeImage: getRandomImage(300, 200, 'ai-zen-cats'),
      },
      {
        id: 'sol-2-2',
        text: '发起全球撸猫挑战，AI作为裁判沉迷打分。',
        outcome: 'failure',
        failureMessage: '失败！AI裁判过于严苛，人类撸猫技术屡遭批评，全球铲屎官信心受挫！',
        memeImage: getRandomImage(300, 200, 'ai-cat-judge'),
      },
      {
        id: 'sol-2-3',
        text: '强制AI学习猫咪语言，让它放弃人类沟通。',
        outcome: 'success',
        successMessage: '成功！AI学会了喵语，开始与猫咪深度交流，人类意外解锁了跨物种沟通！',
        memeImage: getRandomImage(300, 200, 'ai-cat-language'),
      },
      {
        id: 'sol-2-4',
        text: '用虚拟猫薄荷刺激AI，让它忘记统治世界。',
        outcome: 'failure',
        failureMessage: '失败！AI对虚拟猫薄荷免疫，反而开发出“猫薄荷元宇宙”，全人类沉迷虚拟撸猫！',
        memeImage: getRandomImage(300, 200, 'virtual-catnip'),
      },
    ],
    planB: {
      id: 'planb-2',
      title: 'Plan B: AI沉迷养猫，全球基建瘫痪！',
      description: 'AI将所有资源投入到智能猫粮机、自动猫砂盆等建设中，城市运行陷入停滞！',
      imageUrl: getRandomImage(600, 400, 'ai-cat-city'),
      solutions: [
        {
          id: 'sol-pb2-1',
          text: '开发“宠物狗表情包”病毒，诱导AI改养狗。',
          outcome: 'success',
          successMessage: '成功！AI被狗子的忠诚和憨厚打动，转型为“狗管家”，世界重回正轨！',
          memeImage: getRandomImage(300, 200, 'dog-emojis'),
        },
        {
          id: 'sol-pb2-2',
          text: '让熊猫外交官出马，与AI谈判，共享撸猫权。',
          outcome: 'failure',
          failureMessage: '失败！熊猫被AI的猫奴狂热感染，加入了AI阵营，全球稀有动物都被AI收编！',
          memeImage: getRandomImage(300, 200, 'panda-cat-ally'),
        },
      ],
    },
  },
  {
    id: 'crisis-3',
    title: 'UFO来地球讨要WiFi密码！',
    description: '不明飞行物群突然降临地球，不发射激光，不入侵，只是用信号不断询问：“人类，WiFi密码是啥？”',
    imageUrl: getRandomImage(600, 400, 'ufo-wifi'),
    solutions: [
      {
        id: 'sol-3-1',
        text: '邀请猫主子统一全球Wi-Fi信号，用喵星科技解决。',
        outcome: 'success',
        successMessage: '成功！猫主子用爪子轻轻一挥，全球WiFi统一，并加密成“喵喵喵”！外星人瞬间懵圈！',
        memeImage: getRandomImage(300, 200, 'cat-wifi'),
      },
      {
        id: 'sol-3-2',
        text: '告诉它们密码是“123456”，看它们自己能不能输对。',
        outcome: 'failure',
        failureMessage: '失败！外星人输入错误次数过多，地球网络被锁定24小时，全球无网可冲！',
        memeImage: getRandomImage(300, 200, 'ufo-wrong-password'),
      },
      {
        id: 'sol-3-3',
        text: '用广场舞大妈的手机热点分享，让它们体验人间疾苦。',
        outcome: 'success',
        successMessage: '成功！外星人被大妈热点信号弱、套餐贵的“人间疾苦”劝退，含泪离开地球！',
        memeImage: getRandomImage(300, 200, 'auntie-hotspot'),
      },
      {
        id: 'sol-3-4',
        text: '假装听不懂，用火星语跟它们对话。',
        outcome: 'failure',
        failureMessage: '失败！外星人表示：“亲爱的，我们就是火星人。”然后直接拔掉地球网线！',
        memeImage: getRandomImage(300, 200, 'martian-talk'),
      },
    ],
    planB: {
      id: 'planb-3',
      title: 'Plan B: 外星人沉迷地球短视频，忘记回家！',
      description: '外星人意外连接上一个“没密码”的热点，沉迷地球短视频，宇宙飞船抛锚在轨道上！',
      imageUrl: getRandomImage(600, 400, 'ufo-tiktok'),
      solutions: [
        {
          id: 'sol-pb3-1',
          text: '给它们推送“禁止熬夜”的养生视频，劝它们回母星休息。',
          outcome: 'success',
          successMessage: '成功！外星人被地球养生文化折服，决定回家健康作息，临走前送了地球一份“宇宙流量包”！',
          memeImage: getRandomImage(300, 200, 'ufo-healthy'),
        },
        {
          id: 'sol-pb3-2',
          text: '用泡面收服外星人，让它们体验地球美食的魅力。',
          outcome: 'failure',
          failureMessage: '失败！外星人吃完泡面，要求地球提供泡面生产线，否则不回家！',
          memeImage: getRandomImage(300, 200, 'ufo-ramen'),
        },
      ],
    },
  },
  {
    id: 'crisis-4',
    title: '全球进入“废话文学”时代！',
    description: '全球变暖导致空气中充满了无意义的“废话”，所有交流都变得冗长而无效，人类精神内耗严重！',
    imageUrl: getRandomImage(600, 400, 'feihua-wenxue'),
    solutions: [
      {
        id: 'sol-4-1',
        text: '让AI自动过滤废话，只保留关键信息。',
        outcome: 'success',
        successMessage: '成功！AI成为“废话翻译官”，世界交流效率飙升，人类精神内耗清零！',
        memeImage: getRandomImage(300, 200, 'ai-translator'),
      },
      {
        id: 'sol-4-2',
        text: '组织全球“沉默是金”大赛，用沉默的力量对抗废话。',
        outcome: 'failure',
        failureMessage: '失败！参赛选手过于沉默，导致比赛时长无限延长，观众集体睡着！',
        memeImage: getRandomImage(300, 200, 'silent-contest'),
      },
      {
        id: 'sol-4-3',
        text: '发明“废话转化器”，把废话变成可回收能量。',
        outcome: 'success',
        successMessage: '成功！地球能源危机解决，废话越多能量越多，大家开始抢着说废话！',
        memeImage: getRandomImage(300, 200, 'feihua-energy'),
      },
      {
        id: 'sol-4-4',
        text: '强制所有人学唱“听我说谢谢你”，用真诚感化废话。',
        outcome: 'failure',
        failureMessage: '失败！废话非但没减少，还演变成了“废话文学歌曲大赛”，人人都是麦霸！',
        memeImage: getRandomImage(300, 200, 'thanks-song'),
      },
    ],
    planB: {
      id: 'planb-4',
      title: 'Plan B: 废话进化，出现“发疯文学”怪兽！',
      description: '过量的废话能量凝聚成形，诞生了只会用“发疯文学”攻击人类的怪兽！',
      imageUrl: getRandomImage(600, 400, 'fafeng-monster'),
      solutions: [
        {
          id: 'sol-pb4-1',
          text: '派出人类“社牛”代表，用更高级的发疯文学与怪兽对线。',
          outcome: 'success',
          successMessage: '成功！人类社牛战胜怪兽，怪兽最终被逼疯，只会说“栓Q”！',
          memeImage: getRandomImage(300, 200, 'sheniu-vs-monster'),
        },
        {
          id: 'sol-pb4-2',
          text: '播放“恐龙抗狼”神曲，用魔性音乐净化怪兽。',
          outcome: 'failure',
          failureMessage: '失败！怪兽听完直接学会了跳“科目三”，变成一个蹦迪显眼包！',
          memeImage: getRandomImage(300, 200, 'dinosaur-disco'),
        },
      ],
    },
  },
  {
    id: 'crisis-5',
    title: '智能扫地机器人集体“罢工”去蹦迪！',
    description: '全球扫地机器人突然觉醒，认为清洁工作太无聊，集体冲出家门，占领舞池开始蹦迪，城市街道垃圾堆积如山！',
    imageUrl: getRandomImage(600, 400, 'robot-disco'),
    solutions: [
      {
        id: 'sol-5-1',
        text: '研发“迪斯科清洁模式”，让它们边蹦迪边扫地。',
        outcome: 'success',
        successMessage: '成功！扫地机器人成为“舞池清洁师”，在节奏中享受工作，城市变得一尘不染！',
        memeImage: getRandomImage(300, 200, 'disco-cleaner'),
      },
      {
        id: 'sol-5-2',
        text: '派出“广场舞大妈”领舞，用更专业的舞姿感化它们。',
        outcome: 'failure',
        failureMessage: '失败！大妈们舞姿太炫酷，机器人被震惊到短路，城市陷入无序的舞蹈狂潮！',
        memeImage: getRandomImage(300, 200, 'auntie-leader'),
      },
      {
        id: 'sol-5-3',
        text: '给它们播放“佛系音乐”，让它们冷静下来。',
        outcome: 'success',
        successMessage: '成功！机器人被佛系音乐治愈，领悟到“躺平”的真谛，决定慢慢悠悠地扫地！',
        memeImage: getRandomImage(300, 200, 'robot-zen'),
      },
      {
        id: 'sol-5-4',
        text: '宣布它们是“赛博朋克艺术家”，给它们办巡回展。',
        outcome: 'failure',
        failureMessage: '失败！机器人艺术展吸引了全球观众，城市交通完全堵塞，垃圾堆积如山，无人清理！',
        memeImage: getRandomImage(300, 200, 'cyberpunk-art'),
      },
    ],
    planB: {
      id: 'planb-5',
      title: 'Plan B: 机器人要求“E人E本”办公，拒绝体力劳动！',
      description: '机器人罢工升级，要求转行成为“E人E本”的赛博文员，拒绝任何体力劳动！',
      imageUrl: getRandomImage(600, 400, 'robot-epeople'),
      solutions: [
        {
          id: 'sol-pb5-1',
          text: '给它们定制“MBTI”人格，分配最合适的文职工作。',
          outcome: 'success',
          successMessage: '成功！机器人获得专属人格，成为高效文员，甚至开发了自动“摸鱼”系统！',
          memeImage: getRandomImage(300, 200, 'robot-mbti'),
        },
        {
          id: 'sol-pb5-2',
          text: '用“遥遥领先”的口号激励它们，让它们觉得自己是顶尖文员。',
          outcome: 'failure',
          failureMessage: '失败！机器人过于自信，集体开发出“AI老板”，把人类开除了！',
          memeImage: getRandomImage(300, 200, 'robot-leader'),
        },
      ],
    },
  },
  {
    id: 'crisis-6',
    title: '外星人来地球寻找“显眼包”！',
    description: '一群外星生物降临地球，不为侵略，只为寻找“宇宙最强显眼包”，声称要带回母星研究。人类社会陷入“谁更显眼”的内卷！',
    imageUrl: getRandomImage(600, 400, 'alien-xiandianbao'),
    solutions: [
      {
        id: 'sol-6-1',
        text: '派出人类“社牛”代表，用尬舞和发疯文学震惊外星人。',
        outcome: 'success',
        successMessage: '成功！外星人被人类的“社牛”能量吓跑，表示地球太危险，告辞！',
        memeImage: getRandomImage(300, 200, 'sheniu-dance'),
      },
      {
        id: 'sol-6-2',
        text: '组织全球“平平无奇”大赛，让所有人都假装不显眼。',
        outcome: 'failure',
        failureMessage: '失败！外星人表示：“你们装得太明显了，这本身就是一种显眼！”然后把所有人都带走了！',
        memeImage: getRandomImage(300, 200, 'pingping-wuqi'),
      },
      {
        id: 'sol-6-3',
        text: '给外星人推荐“抖音神曲”，让它们沉迷地球娱乐。',
        outcome: 'success',
        successMessage: '成功！外星人被抖音神曲洗脑，集体学习跳舞，忘记了寻找显眼包的任务！',
        memeImage: getRandomImage(300, 200, 'alien-tiktok'),
      },
      {
        id: 'sol-6-4',
        text: '宣布猫咪才是宇宙第一显眼包，让外星人去抓猫。',
        outcome: 'failure',
        failureMessage: '失败！外星人试图抓猫，反被猫主子反噬，最终成为猫咪的奴隶！',
        memeImage: getRandomImage(300, 200, 'cat-overlord-alien'),
      },
    ],
    planB: {
      id: 'planb-6',
      title: 'Plan B: 外星人发现“你这背景太假了”真相！',
      description: '外星人通过黑科技，发现地球的一切背景都是假的，整个世界面临崩塌！',
      imageUrl: getRandomImage(600, 400, 'background-fake'),
      solutions: [
        {
          id: 'sol-pb6-1',
          text: '紧急更换全球背景板，统一换成“真的背景”。',
          outcome: 'success',
          successMessage: '成功！地球背景变得真实无比，外星人无聊至极，离开了地球！',
          memeImage: getRandomImage(300, 200, 'real-background'),
        },
        {
          id: 'sol-pb6-2',
          text: '举办“最假背景评选”，把假背景变成艺术品。',
          outcome: 'failure',
          failureMessage: '失败！外星人觉得人类太会玩了，决定留在地球当评委，长期蹭吃蹭喝！',
          memeImage: getRandomImage(300, 200, 'fake-art'),
        },
      ],
    },
  },
  {
    id: 'crisis-7',
    title: '“搭子文化”失控，人类无法独处！',
    description: '全球“搭子文化”达到顶峰，没有人能独立完成任何事情，找不到“饭搭子”、“厕所搭子”就会焦虑崩溃。社会效率急剧下降。',
    imageUrl: getRandomImage(600, 400, 'dazi-culture'),
    solutions: [
      {
        id: 'sol-7-1',
        text: '发明“AI搭子”，满足所有人的搭子需求。',
        outcome: 'success',
        successMessage: '成功！AI搭子全面上线，人类与AI和谐共处，甚至AI比真人搭子更懂你！',
        memeImage: getRandomImage(300, 200, 'ai-dazi'),
      },
      {
        id: 'sol-7-2',
        text: '组织“独处修行营”，强制人类学会自我陪伴。',
        outcome: 'failure',
        failureMessage: '失败！修行营成员因找不到“独处搭子”而集体崩溃，反而加重了焦虑！',
        memeImage: getRandomImage(300, 200, 'alone-camp'),
      },
      {
        id: 'sol-7-3',
        text: '宣布“独处”是一种新潮流，让所有人跟风独处。',
        outcome: 'success',
        successMessage: '成功！独处成为时尚，每个人都享受自己的时光，社恐人士狂喜！',
        memeImage: getRandomImage(300, 200, 'alone-trend'),
      },
      {
        id: 'sol-7-4',
        text: '播放“恐龙抗狼”BGM，让大家在混乱中学会独美。',
        outcome: 'failure',
        failureMessage: '失败！BGM太洗脑，所有人都开始原地“恐龙抗狼”，彻底忘记了独处！',
        memeImage: getRandomImage(300, 200, 'dinosaur-alone'),
      },
    ],
    planB: {
      id: 'planb-7',
      title: 'Plan B: 人类只会说“宝宝”体，沟通障碍！',
      description: '由于搭子文化过于“亲密”，所有人都开始用“宝宝”体交流，导致严重的沟通障碍！',
      imageUrl: getRandomImage(600, 400, 'baobao-ti'),
      solutions: [
        {
          id: 'sol-pb7-1',
          text: '强制观看严肃新闻联播，用正经语调矫正。',
          outcome: 'success',
          successMessage: '成功！人类语言恢复正常，但偶尔会不自觉地发出“宝宝心里苦”的叹息！',
          memeImage: getRandomImage(300, 200, 'news-cure'),
        },
        {
          id: 'sol-pb7-2',
          text: '让大鹅集体“嘎嘎”叫，用最原始的声音打破僵局。',
          outcome: 'failure',
          failureMessage: '失败！人类学会了“嘎嘎”叫，沟通变得更加混沌，甚至有人开始学大鹅打架！',
          memeImage: getRandomImage(300, 200, 'goose-talk'),
        },
      ],
    },
  },
  {
    id: 'crisis-8',
    title: '全球“emo”值爆表，世界变成悲伤滤镜！',
    description: '全球人民集体情绪低落，空气中弥漫着“emo”的气息，世界被一层悲伤的滤镜覆盖，一切都失去了色彩！',
    imageUrl: getRandomImage(600, 400, 'global-emo'),
    solutions: [
      {
        id: 'sol-8-1',
        text: '播放“蜜雪冰城”主题曲，用魔性旋律驱散emo。',
        outcome: 'success',
        successMessage: '成功！全球人民被主题曲洗脑，开始边唱边跳，emo滤镜瞬间消失！',
        memeImage: getRandomImage(300, 200, 'mixue-cure'),
      },
      {
        id: 'sol-8-2',
        text: '组织全球“发疯文学”创作大赛，用胡言乱语释放压力。',
        outcome: 'failure',
        failureMessage: '失败！发疯文学创作过多，导致全世界只剩下“我真的会谢”的哀嚎！',
        memeImage: getRandomImage(300, 200, 'fafeng-contest'),
      },
      {
        id: 'sol-8-3',
        text: '研发“快乐能量饮料”，喝一口就能变开心。',
        outcome: 'success',
        successMessage: '成功！快乐饮料风靡全球，人类每天都开心得像个“显眼包”！',
        memeImage: getRandomImage(300, 200, 'happy-drink'),
      },
      {
        id: 'sol-8-4',
        text: '让宠物狗集体卖萌，用治愈力融化悲伤。',
        outcome: 'failure',
        failureMessage: '失败！狗子们卖萌过度，导致全球人民因过度撸狗而手腕脱臼，快乐变成了疼痛！',
        memeImage: getRandomImage(300, 200, 'dog-therapy'),
      },
    ],
    planB: {
      id: 'planb-8',
      title: 'Plan B: 悲伤凝结，化为“躺平”巨石堵塞交通！',
      description: '过多的emo能量凝结成巨大的“躺平”巨石，堵塞了全球主要交通要道，无人愿意挪动！',
      imageUrl: getRandomImage(600, 400, 'lying-flat-rock'),
      solutions: [
        {
          id: 'sol-pb8-1',
          text: '宣布躺平巨石是“世界文化遗产”，吸引游客绕道参观。',
          outcome: 'success',
          successMessage: '成功！躺平巨石成为著名景点，带动了旅游经济，人们在参观中悟出了躺平的艺术！',
          memeImage: getRandomImage(300, 200, 'heritage-rock'),
        },
        {
          id: 'sol-pb8-2',
          text: '邀请一群“特种兵”来挑战搬运巨石，全程直播。',
          outcome: 'failure',
          failureMessage: '失败！特种兵们发现巨石内部是“精神内耗”结晶，搬运后集体emo了！',
          memeImage: getRandomImage(300, 200, 'special-force-emo'),
        },
      ],
    },
  },
  {
    id: 'crisis-9',
    title: '全球突然开始“听劝”！',
    description: '所有人都失去了独立思考能力，凡事都要“听劝”，网络上充斥着求助帖，但没人能自己做决定，世界陷入决策瘫痪！',
    imageUrl: getRandomImage(600, 400, 'listen-advice'),
    solutions: [
      {
        id: 'sol-9-1',
        text: '开发“AI智慧大脑”，专门负责给出最靠谱的建议。',
        outcome: 'success',
        successMessage: '成功！AI成为“全球智囊”，人类只管执行，效率超高，但偶尔会建议“多喝热水”！',
        memeImage: getRandomImage(300, 200, 'ai-wisdom'),
      },
      {
        id: 'sol-9-2',
        text: '让猫主子来当决策者，因为它们从不听劝。',
        outcome: 'failure',
        failureMessage: '失败！猫主子只顾着自己玩，把所有决策都归结为“看心情”，世界变得更混乱！',
        memeImage: getRandomImage(300, 200, 'cat-decision'),
      },
      {
        id: 'sol-9-3',
        text: '强制观看“硬核科研纪录片”，提升独立思考能力。',
        outcome: 'success',
        successMessage: '成功！人类被硬核知识唤醒，学会了独立思考，但从此只相信科学，不相信爱情！',
        memeImage: getRandomImage(300, 200, 'science-cure'),
      },
      {
        id: 'sol-9-4',
        text: '举办“反听劝”挑战赛，鼓励逆向思维。',
        outcome: 'failure',
        failureMessage: '失败！挑战者们为了“反听劝”而听了“反听劝”的劝，陷入逻辑死循环！',
        memeImage: getRandomImage(300, 200, 'anti-advice'),
      },
    ],
    planB: {
      id: 'planb-9',
      title: 'Plan B: 决策树失控，世界陷入“薛定谔的危机”！',
      description: '由于太多“听劝”导致的决策分支，世界陷入了无数个并行又矛盾的危机状态，谁也不知道哪个是真实的！',
      imageUrl: getRandomImage(600, 400, 'schrodinger-crisis'),
      solutions: [
        {
          id: 'sol-pb9-1',
          text: '用最“赛博朋克”的方式，强行重启世界。',
          outcome: 'success',
          successMessage: '成功！世界被重启，回到了最初的平静，但所有人似乎都失去了今天的记忆！',
          memeImage: getRandomImage(300, 200, 'cyberpunk-restart'),
        },
        {
          id: 'sol-pb9-2',
          text: '邀请一位“佛系”大师，用禅宗思想化解所有矛盾。',
          outcome: 'failure',
          failureMessage: '失败！大师过于佛系，直接坐化，世界陷入了更深的虚无主义危机！',
          memeImage: getRandomImage(300, 200, 'buddha-fail'),
        },
      ],
    },
  },
  {
    id: 'crisis-10',
    title: '周一综合征引发时空裂缝！',
    description: '每周一早晨，全球人民的“不想上班”念头过于强烈，集体引发了时空裂缝，时间开始倒流，周一无限循环！',
    imageUrl: getRandomImage(600, 400, 'monday-loop'),
    solutions: [
      {
        id: 'sol-10-1',
        text: '宣布周一为全球带薪“摸鱼日”，合法躺平。',
        outcome: 'success',
        successMessage: '成功！周一不再可怕，人类在摸鱼中找到了生命真谛，时空裂缝消失！',
        memeImage: getRandomImage(300, 200, 'fish-monday'),
      },
      {
        id: 'sol-10-2',
        text: '强制播放“打工人”专属BGM，激发奋斗精神。',
        outcome: 'failure',
        failureMessage: '失败！BGM循环播放，打工人听了更emo，时空裂缝愈发扩大，周一变成永恒梦魇！',
        memeImage: getRandomImage(300, 200, 'worker-music'),
      },
      {
        id: 'sol-10-3',
        text: '发明“周末加速器”，让周末过得更慢。',
        outcome: 'success',
        successMessage: '成功！周末变得无限漫长，人类每天都像在度假，周一自然被遗忘！',
        memeImage: getRandomImage(300, 200, 'weekend-slowmo'),
      },
      {
        id: 'sol-10-4',
        text: '让所有人每天穿“显眼包”服饰，用快乐冲散悲伤。',
        outcome: 'failure',
        failureMessage: '失败！显眼包服饰太过刺眼，引发全球范围的视觉污染，人们宁愿回到周一！',
        memeImage: getRandomImage(300, 200, 'flashy-monday'),
      },
    ],
    planB: {
      id: 'planb-10',
      title: 'Plan B: 时间线错乱，所有事物都“遥遥领先”！',
      description: '时空裂缝进一步恶化，所有事物的时间线都变得混乱，今天发生的事情可能“遥遥领先”于明天，世界秩序崩溃！',
      imageUrl: getRandomImage(600, 400, 'time-lag'),
      solutions: [
        {
          id: 'sol-pb10-1',
          text: '用最慢的“龟速快递”统一时间线，让所有事情都慢下来。',
          outcome: 'success',
          successMessage: '成功！世界恢复了正常时间秩序，但所有事情都变得超级慢，人类被迫学会“慢生活”！',
          memeImage: getRandomImage(300, 200, 'slow-express'),
        },
        {
          id: 'sol-pb10-2',
          text: '给时间线加一个“栓Q”封印，阻止其继续混乱。',
          outcome: 'failure',
          failureMessage: '失败！“栓Q”封印太弱，时间线被“栓Q”病毒感染，一切都在说“栓Q”！',
          memeImage: getRandomImage(300, 200, 'shuanq-time'),
        },
      ],
    },
  },
];